# Form implementation generated from reading ui file 'newremote.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(295, 478)
        MainWindow.setMaximumSize(QtCore.QSize(295, 478))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.powerButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.powerButton.setGeometry(QtCore.QRect(220, 10, 71, 41))
        self.powerButton.setAutoExclusive(False)
        self.powerButton.setObjectName("powerButton")
        self.muteButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.muteButton.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.muteButton.setAutoExclusive(False)
        self.muteButton.setObjectName("muteButton")
        self.volumeUpButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volumeUpButton.setGeometry(QtCore.QRect(10, 220, 81, 91))
        self.volumeUpButton.setObjectName("volumeUpButton")
        self.volumeDownButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.volumeDownButton.setGeometry(QtCore.QRect(10, 320, 81, 91))
        self.volumeDownButton.setObjectName("volumeDownButton")
        self.channelUpButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channelUpButton.setGeometry(QtCore.QRect(200, 220, 81, 91))
        self.channelUpButton.setObjectName("channelUpButton")
        self.channelDownButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.channelDownButton.setGeometry(QtCore.QRect(200, 320, 81, 91))
        self.channelDownButton.setObjectName("channelDownDown")
        self.volumeBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.volumeBar.setGeometry(QtCore.QRect(10, 190, 118, 23))
        self.volumeBar.setProperty("value", 24)
        self.volumeBar.setObjectName("volumeBar")
        self.channelSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.channelSlider.setGeometry(QtCore.QRect(170, 240, 22, 160))
        self.channelSlider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.channelSlider.setObjectName("channelSlider")
        self.tvChannel = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.tvChannel.setGeometry(QtCore.QRect(10, 50, 271, 131))
        self.tvChannel.setObjectName("tvChannel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 295, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.powerButton.setText(_translate("MainWindow", "Power"))
        self.muteButton.setText(_translate("MainWindow", "Mute"))
        self.volumeUpButton.setText(_translate("MainWindow", "Volume Up"))
        self.volumeDownButton.setText(_translate("MainWindow", "Volume Down"))
        self.channelUpButton.setText(_translate("MainWindow", "Channel Up"))
        self.channelDownButton.setText(_translate("MainWindow", "Channel Down"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
